export const payrollList = [
  {
    id: 1,
    src: "/img/dibble.png",
    position: "UX/UI Designer",
    location: "Company name in Miami, Florida",
    duration: "1 Mar - 7 Mar",
    memoNumber: "123123456",
    totalAmount: "2,305.00",
    perHour: "$15",
    workingHours: 65,
  },
  {
    id: 2,
    src: "/img/two-dots.png",
    position: "UX/UI Designer",
    location: "Company name in Miami, Florida",
    duration: "1 Mar - 7 Mar",
    memoNumber: "123123456",
    totalAmount: "2,305.00",
    perHour: "$15",
    workingHours: 65,
  },
  {
    id: 3,
    src: "/img/apple.png",
    position: "UX/UI Designer",
    location: "Company name in Miami, Florida",
    duration: "1 Mar - 7 Mar",
    memoNumber: "123123456",
    totalAmount: "2,305.00",
    perHour: "$15",
    workingHours: 65,
  }
]